First draft of sccp documentation.
distributed-technologies/wiki pull request #13
Opened 2021-06-29 05:54 UTC by jacobcrawford

2021-06-29 08:38 UTC, MartinSchmidt commented on SCCP.md
> +- [ ] TTE
TEE?

2021-06-29 08:51 UTC, jaxels10 requested changes

2021-06-29 08:51 UTC, jaxels10 commented on SCCP.md
> +**Secure compute and communication platform** has emerged as a weapon to deal with some of the problems the energisystem is facing, as the energy production is becomming more renewable. One of the bi
I think the "has emerged as a weapon" might be a bit colorful 😄.

2021-06-29 08:51 UTC, jaxels10 commented on SCCP.md
> +**Secure compute and communication platform** has emerged as a weapon to deal with some of the problems the energisystem is facing, as the energy production is becomming more renewable. One of the bi
Is it the energy production that is becoming more renewable or is it the energy?

2021-06-29 08:51 UTC, jaxels10 commented on SCCP.md
> +**Secure compute and communication platform** has emerged as a weapon to deal with some of the problems the energisystem is facing, as the energy production is becomming more renewable. One of the bi
since we write communication, should compute also be computation? I am unsure

2021-06-29 08:51 UTC, jaxels10 commented on SCCP.md
> +The platform is essentially a kubernetes cluster with an agent supporting the Gitops workflow. Following the Gitops workflow all infrastructure is configured as code in seperate service git repositor
should agent be called operator instead? I think that is what it is in GitOps.

2021-06-29 08:51 UTC, jaxels10 commented on SCCP.md
> +The platform is essentially a kubernetes cluster with an agent supporting the Gitops workflow. Following the Gitops workflow all infrastructure is configured as code in seperate service git repositor
seperate -> separate
Also, I think it sounds weird to say service git repositories, since people might not be aware of what we mean by service.

2021-06-29 08:51 UTC, jaxels10 commented on SCCP.md
> +The platform is cloud agnostic, meaning that will be able to be setup both in bare metal situations as well as deployed in any cloud provider thus greatly increasing the stability and scalability of
```suggestion
The platform is cloud agnostic, meaning that it will be able to be deployed onto both bare metal as well as on any cloud provider thus greatly increasing the stability and scalability of the platform, because vendor lock-in is avoided. Compiling our own Linux operating system, we reduce the dependencies and packages to a minimum, further reducing the potential attack vectors for adversaries. Basically, the only features enabled are the ones that are needed to start up a Kubernetes cluster. 
```

2021-06-29 08:51 UTC, jaxels10 commented on SCCP.md
> +The platform is cloud agnostic, meaning that will be able to be setup both in bare metal situations as well as deployed in any cloud provider thus greatly increasing the stability and scalability of
I don't quite understand how being cloud agnostic increases the stability and scalability of the platform. Can we give some arguments for that?

2021-06-29 08:51 UTC, jaxels10 commented on SCCP.md
> +Taking the next step in security the platform is enabeling a feature to fuse hardware and software security in a trusted execution environment. In its essence this means that the hardware will not ru
```suggestion
Taking the next step in security the platform is enabling a feature to fuse hardware and software security in a trusted execution environment. In its essence this means that the hardware will not run any software that does not have the correct digital signatures and the software will not run on any hardware that does not have the correct digital signature.
```

2021-06-29 08:51 UTC, jaxels10 commented on SCCP.md
> +**Secure compute and communication platform** has emerged as a weapon to deal with some of the problems the energisystem is facing, as the energy production is becomming more renewable. One of the bi
```suggestion
**Secure compute and communication platform** has emerged as a weapon to deal with some of the problems the energy system is facing, as the energy production is becoming more renewable. One of the bigger problems is that renewable energy forces the system to run close to the edge as the production of energy becomes highly fluctuating. This calls for improved algorithms that helps operators of the critical systems make decisions. The SCCP is the foundation on which these models will live in any given situation, providing a platform that raises the bar for security both for communication and computation. 
```

2021-06-29 08:51 UTC, jaxels10 commented on SCCP.md
> +All technologies that is used to build the SCCP is open source.
```suggestion
All technologies that are used to build the SCCP are open source.
```

2021-06-29 08:51 UTC, jaxels10 commented on SCCP.md
> +ArgoCD is used as the GitOps tool that contineously delivers changes to the platform based on pull request changes.
```suggestion
ArgoCD is used as the GitOps tool that continuously delivers changes to the platform based on changes in the environment repositories.
```

2021-06-29 08:51 UTC, jaxels10 commented on SCCP.md
> +Prometheus is used as the monitoring time series database, that contineously scrabes metrics from all containers that expose them.
```suggestion
Prometheus is used as the monitoring time series database, that continuously scrapes metrics from all containers that expose them.
```

2021-06-29 08:51 UTC, jaxels10 commented on SCCP.md
> +Ceph is used through an [opensource Rook operator](https://github.com/rook/rook) as a distributed persistent storage, handeling jobs like replication to avoid data loss at machine failiure.
```suggestion
Ceph is used through an [opensource Rook operator](https://github.com/rook/rook) as a distributed persistent storage, handling jobs like replication to avoid data loss at machine failure. 
```

2021-06-29 08:51 UTC, jaxels10 commented on SCCP.md
> +Metallb is used as the software loadbalancer delegating ips to services that needs a static ip.
```suggestion
Metallb is used as the software loadbalancer delegating IPs to services that needs a static IP. 
```

2021-06-29 08:51 UTC, jaxels10 commented on SCCP.md
> +Traefik is used an ingress controller handeling ingress events to route communication.
```suggestion
Traefik is used as an ingress controller handling ingress events to route communication.
```

2021-06-29 08:51 UTC, jaxels10 commented on SCCP.md
> +- [ ] One click build pipeline
Is this a complete roadmap?

2021-06-29 14:50 UTC, jacobcrawford commented on SCCP.md
> +The platform is cloud agnostic, meaning that will be able to be setup both in bare metal situations as well as deployed in any cloud provider thus greatly increasing the stability and scalability of
See new text.

2021-06-29 14:56 UTC, jacobcrawford commented on SCCP.md
> +- [ ] One click build pipeline
This is just meant as an example of what we could but in the docs to reflect the status of the platform, and it should not be seen as an exhaustive list of features. If we choose to keep it, we will need to take some high-level features from the RTP and put in here.

2021-06-30 11:28 UTC, MartinSchmidt requested changes
I have left a series of comments.

2021-06-30 11:28 UTC, MartinSchmidt commented on SCCP.md
> +**Secure compute and communication platform** has emerged as a tool to deal with some of the problems the energy system is facing, as the production is shifting towards more renewable energy. One of
I think we should look at it more broadly, we made the SCCP platform to be able to define a secure environment in code. The environment are required to be strictly controlled with the help of TEE and signed code, which ensures only signed and allowed code are executed on the platform.

Renewable energy itself is not the reason alone why we are doing this.

2021-06-30 11:28 UTC, MartinSchmidt commented on SCCP.md
> +The platform is essentially a Kubernetes cluster with an operator supporting the Gitops workflow. Following the Gitops workflow, all infrastructure is configured as code in separate git repositories
"GitOps" ..

The environment itself should be defined based on a single repository in the near future, describing the infrastructure provisioning, enabled system services, and referring hosted applications environment repositories.

I think this should be made more clear.

2021-06-30 11:28 UTC, MartinSchmidt commented on SCCP.md
> +#### [ArgoCD](https://github.com/argoproj/argo-cd/)
I don't think this list is essential here. 
I would suggest moving it to a seperate file.
More over we should add a notice describing the licenses for our dependencies, similar to DataHub
https://github.com/Energinet-DataHub/green-energy-hub/blob/main/NOTICE.md

2021-07-01 06:52 UTC, jacobcrawford commented on SCCP.md
> +**Secure compute and communication platform** has emerged as a tool to deal with some of the problems the energy system is facing, as the production is shifting towards more renewable energy. One of
New text.

2021-07-01 07:06 UTC, jacobcrawford commented on SCCP.md
> +#### [ArgoCD](https://github.com/argoproj/argo-cd/)
Since we do not have a single environment repository yet, should we make a new task on the NOTICE docs?

2021-07-01 07:08 UTC, jacobcrawford commented on SCCP.md
> +#### [ArgoCD](https://github.com/argoproj/argo-cd/)
I have added a draft of the notice. We need to input email and dependencies.

2021-07-05 13:11 UTC, skovbakke requested changes
My few comments

2021-07-05 13:11 UTC, skovbakke commented on SCCP.md
> +The platform is cloud-agnostic, meaning that it will be able to be deployed both in bare metal situations as well as on deployed in any cloud provider thus greatly increasing the stability and scalab
I do not see how being cloud-agnostic makes the platform more scalable. Deploying in the cloud at multiple availability zones provides the same "outage"-protection. What is meant by "security event"?

2021-07-05 13:11 UTC, skovbakke commented on SCCP.md
> +Taking the next step in security, the platform is enabling a feature to fuse hardware and software security in a trusted execution environment. In its essence, this means that the hardware will not r
In essense i think we should hold of on putting these claims into writing untill they are developed.

2021-07-09 11:10 UTC, MartinSchmidt commented on NOTICE.md
> +Energinet and any contributors reserve all others rights, whether under their respective copyrights, patents, licenses, or trademarks, whether by implication, estoppel or otherwise.
From my knowledge, the NOTICE.md file is here to tell what is referenced from within the repository, and to make sure that all their copyrights and licenses are still upheld. So people understand that these parts are not covered under our license.

2021-07-09 11:11 UTC, MartinSchmidt commented on SCCP.md
> +
Agreed with both points.

2021-07-09 11:12 UTC, MartinSchmidt commented on SCCP.md
> +Taking the next step in security, the platform is enabling a feature to fuse hardware and software security in a trusted execution environment. In its essence, this means that the hardware will not r
But we could still tell what the goal is, as long as it is clear that it is not yet fully developed.

2021-07-19 10:22 UTC, jacobcrawford commented on NOTICE.md
> +Energinet and any contributors reserve all others rights, whether under their respective copyrights, patents, licenses, or trademarks, whether by implication, estoppel or otherwise.
@MartinSchmidt should I add all the open-source libraries we use?

2021-07-20 07:40 UTC, skovbakke approved these changes
I think we should merge this and start a new branch / pr  if we have additional suggestions

2021-07-20 11:43 UTC, MartinSchmidt approved these changes

2021-07-20 11:45 UTC, MartinSchmidt commented on NOTICE.md
> +Energinet and any contributors reserve all others rights, whether under their respective copyrights, patents, licenses, or trademarks, whether by implication, estoppel or otherwise.
The notice should exist in each repo from my understanding, and there each reference what was is used.
So i think this is good for now.

2021-07-21 07:48 UTC, jaxels10 approved these changes

2021-07-21 07:50 UTC, merged