Moved umbrella chart docs into helm folder.
distributed-technologies/wiki pull request #16
Opened 2021-07-02 08:21 UTC by jacobcrawford

Fixed path for docs and made reference from main readme.

2021-07-02 09:15 UTC, skovbakke requested changes

2021-07-02 09:15 UTC, skovbakke commented on README.md
> +Documentation related to helm can be found in [helm folder](./helm/index.md)
I think we should move the index to a single index in the README file.

2021-07-02 09:33 UTC, skovbakke commented on README.md
> +Documentation related to helm can be found in [helm folder](./helm/index.md)
Nicely done.

2021-07-02 09:35 UTC, skovbakke approved these changes
Looks good

2021-07-05 11:33 UTC, skovbakke approved these changes
Very nice

2021-07-05 11:34 UTC, jaxels10 approved these changes
Ok.

2021-07-05 11:34 UTC, merged