Feature/release pipeline
distributed-technologies/wiki pull request #17
Opened 2021-07-05 14:56 UTC by jacobcrawford

2021-07-20 11:47 UTC, MartinSchmidt submitted a review, later dismissed
Looks good.

2021-07-21 07:44 UTC, skovbakke requested changes
A little wording fix

2021-07-21 07:44 UTC, skovbakke commented on helm/release-pipeline.md
> + 4. push the asset to our [helm registry](https://github.com/distributed-technologies/helm-repository) and update the index file for the helm registry
```suggestion
 1. package the Helm chart.
 2. create a GitHub release.
 3. attach the package as an asset to the release.
 4. push the asset to our [helm registry](https://github.com/distributed-technologies/helm-repository) and update the index file for the helm registry.
```
Made sure all the steps are worded the same way.

2021-07-21 07:48 UTC, skovbakke approved these changes
nice

2021-07-26 07:34 UTC, MartinSchmidt approved these changes

2021-07-26 07:35 UTC, merged