Added template for bump version workflow and docs.
distributed-technologies/wiki pull request #2
Opened 2021-03-02 17:07 UTC by jacobcrawford

2021-03-03 10:16 UTC, MartinSchmidt requested changes
Move to a seperate md file in the git folder.

2021-03-03 10:16 UTC, MartinSchmidt commented on templates/github-workflows/bump_version_main.yaml
> +        VERBOSE: true
Add newline

2021-03-04 06:38 UTC, MartinSchmidt requested changes
Move Git workflows to file in /git folder

2021-03-04 07:27 UTC, MartinSchmidt requested changes

2021-03-04 07:27 UTC, MartinSchmidt commented on README.md
> +### Git workflows
- [ ] Move to new /git folder

2021-03-04 07:31 UTC, MartinSchmidt requested changes

2021-03-04 07:31 UTC, MartinSchmidt commented on README.md
> +This means that if you e.g. want to bump the version v1.0.0 to v1.0.1 your commit message to main should include the string '#patch'. There is no default version bump and therefore this workflow will
something here test

- [ ] test

2021-03-04 07:32 UTC, MartinSchmidt requested changes
to review comment.

2021-03-04 07:32 UTC, MartinSchmidt commented on README.md
> +
test here 1

- [ ] a
- [ ] b

2021-03-04 07:32 UTC, MartinSchmidt commented on README.md
> +
test here b

- [ ] c
- [ ] d

2021-03-04 08:40 UTC, skovbakke requested changes

2021-03-04 08:40 UTC, skovbakke commented on README.md
> +This means that if you e.g. want to bump the version v1.0.0 to v1.0.1 your commit message to main should include the string '#patch'. There is no default version bump and therefore this workflow will
Maybe add a paragraph on how to use the workflow in you project, i.e. where does the [.yaml file](https://github.com/distributed-technologies/wiki/pull/2/files#diff-bcf64a2380e5d1f5bd1f4b4d8eef3de98ea57164377d856c0d51b825c9a39025) go and what needs to be done (if anything) to make it work.

2021-03-04 09:38 UTC, MartinSchmidt requested changes
Almost perfect 😅 I suggest changing the header size.

2021-03-04 09:38 UTC, MartinSchmidt commented on git/workflows.md
> +#### Git workflows
```suggestion
# Git workflows
```

- [ ] I suggest changing the header, it is smaller than the version bumb header..

2021-03-04 10:06 UTC, MartinSchmidt approved these changes

2021-03-04 10:24 UTC, skovbakke approved these changes
Looks good

2021-03-04 10:41 UTC, merged