Feature/test requirements
distributed-technologies/wiki pull request #20
Opened 2021-07-26 14:22 UTC by skovbakke

Added a section explaining our use of tests in proxy Helm charts.

2021-07-27 12:07 UTC, jacobcrawford commented on helm/test.md
> +Generally the tests are located in a Helm proxy chart for the service. The tests are located in a folder called `test`. Before any merge of changes onto the main branch, a github workflow automatical
For consistency, I think we should use the helm test hooks for acceptance tests.  
Then a test is described in yaml as a Pod that runs a test script, and we can use the `helm test xxx` command as a test engine. That way we can run tests inside the cluster and we are not dependent on the host system having packages installed.
See https://github.com/distributed-technologies/services-kafka/blob/main/.github/workflows/test_create.yaml
for reference.

2021-07-28 11:17 UTC, jaxels10 requested changes

2021-07-28 11:17 UTC, jaxels10 commented on helm/test.md
> +All of the services develloped for the platform should pass basic acceptance tests before they are deployed.
```suggestion
All of the services developed for the platform should pass basic acceptance tests before they are deployed. 
```

2021-07-28 11:17 UTC, jaxels10 commented on helm/test.md
> +The tests should verify the core functionality of the service. The tests should catch configuration issues or problems with the service and ensure that the service functions as is inteded.
```suggestion
The tests should verify the core functionality of the service. The tests should catch configuration issues or problems with the service and ensure that the service functions as intended. 
```

2021-07-28 13:15 UTC, skovbakke commented on helm/test.md
> +Generally the tests are located in a Helm proxy chart for the service. The tests are located in a folder called `test`. Before any merge of changes onto the main branch, a github workflow automatical
```suggestion
Generally the tests are located in a Helm proxy chart for the service. The tests are located in a folder called `test`. Before any merge of changes onto the main branch, a github workflow automatically runs the test in a `kind` cluster. 
See https://github.com/distributed-technologies/services-kafka/blob/main/.github/workflows/test_create.yaml
for reference.
```

2021-07-29 09:05 UTC, jaxels10 approved these changes
Looks good.

2021-07-30 06:14 UTC, MartinSchmidt approved these changes

2021-07-30 06:31 UTC, merged