Feature/trusted execution
distributed-technologies/wiki pull request #24
Opened 2021-09-10 08:22 UTC by SomeFriendlyGhost

Added commits together and created  a pull request for review

2021-09-10 09:04 UTC, jacobcrawford requested changes
In general I could use some kind of problem statement.
What is our current problem?
How can a TPM module help solve this problem?

2021-09-12 17:58 UTC, klausenbusk commented on trusted_execution/tpm.md
> +Because the SAPI is still has a high complexity TCG made a specification for an even further abstraction with the Enhanced system API [(ESAPI) specifcation pdf](https://trustedcomputinggroup.org/wp-c
```suggestion
Because the SAPI has a high complexity [TCG made a specification for an even further abstraction with the Enhanced system API](https://trustedcomputinggroup.org/wp-content/uploads/TSS_ESAPI_v1p0_r08_pub.pdf).
```

2021-09-12 17:58 UTC, klausenbusk commented on trusted_execution/tpm.md
> +Intel txt provides an extension to the intel chip set and therefore enables a hard coupling between the hardware used, and the system.
```suggestion
Intel txt provides an extension to Intel's chipset and therefore enables a hard coupling between the hardware used, and the system.
```

2021-09-12 17:58 UTC, klausenbusk commented on trusted_execution/tpm.md
> +The result is a hardened chain of trust from secure boot to TPM measurements by utilizing the access to the Intel chip set. Intel® Trusted Execution Technology  (Intel® TXT) Enabling Guide
```suggestion
The result is a hardened chain of trust from secure boot to TPM measurements by utilizing the access to the Intel's chipset. Intel® Trusted Execution Technology  (Intel® TXT) Enabling Guide 
```

2021-09-12 17:58 UTC, klausenbusk commented on trusted_execution/tpm.md
> +Intel txt creates a secured environment for each application to run, which protects an application against software attacks from outside the environment Intel® Trusted Execution Technology (Intel® TX
```suggestion
Intel TXT creates a secured environment for each application to run, which protects an application against software attacks from outside the environment Intel® Trusted Execution Technology (Intel® TXT) Overview .
```

2021-09-12 17:58 UTC, klausenbusk commented on trusted_execution/tpm.md
> +Because the stack uses the tool [TrouSerS](https://sourceforge.net/p/trousers/trousers/ci/master/tree/) It is unsure if this stack supports x86 instructions and TPM v2.
```suggestion
Because the stack uses the tool [TrouSerS](https://sourceforge.net/p/trousers/trousers/ci/master/tree/) It is unclear if this stack supports the x86 architecture and TPM 2.0.
```

2021-09-12 17:58 UTC, klausenbusk commented on trusted_execution/tpm.md
> +AMD has firmware TPM (FTPM) since the Ryzen 2500 CPU that only require us to enable it in the BIOS settings Here’s what you’ll need to upgrade to Windows 11 .
```suggestion
AMD has firmware TPM (FTPM) since the Ryzen 2500 CPU that only require us to enable it in the BIOS.
```

2021-09-12 17:58 UTC, klausenbusk commented on trusted_execution/tpm.md
> +## Self configured tpm stack
```suggestion
## Self configured TPM stack
```

2021-09-12 17:58 UTC, klausenbusk commented on trusted_execution/tpm.md
> +This option gives the platform owner, the possibility to create and support the chain of trust without being hardware restricted as much. In this instance we would be able to use the secure boot buil
```suggestion
This option gives the platform owner, the possibility to create and support the chain of trust without being hardware restricted as much. In this instance we would be able to use the Secure Boot and apply a discrete TPM with a TSS that gives us everything we need to operate a TPM.
```

2021-09-12 17:58 UTC, klausenbusk commented on trusted_execution/tpm.md
> +- AMD FTPM
```suggestion
- Intel TXT
- AMD FTPM
- Self configured TPM stack
```

2021-09-12 17:58 UTC, klausenbusk commented on trusted_execution/tpm.md
> +It is built as shown in the picture below with a non volatile storage to keep our certificates and encryption keys, a set of secure platform registers for hash values, and a interface enabling us to
Please add the image to the repo with proper credit. We want to avoid link rot :)

2021-09-12 17:58 UTC, klausenbusk commented on trusted_execution/tpm.md
> +Next is the marshaling and unmarshaling API (MUAPI) specification. It makes up a layer which is responsible for translating between the language specific representation (C) and the network data strea
```suggestion
Next is the marshaling and unmarshaling API [(MUAPI) specification](https://trustedcomputinggroup.org/wp-content/uploads/TCG_TSS_Marshaling_Unmarshaling_API_v1p0_r07_pub.pdf). It makes up a layer which is responsible for translating between the language specific representation (C) and the network data stream.
```

2021-09-12 17:58 UTC, klausenbusk commented on trusted_execution/tpm.md
> +First off we have the Tab (TPM access broker) and resource manager (RM) specification. IT describes the physical capabilities and defines what kind of work the Tab and RM can do for the upper TSS lay
```suggestion
First off we have the [Tab (TPM access broker) and resource manager (RM) specification](https://trustedcomputinggroup.org/wp-content/uploads/TSS_2p0_TAB_ResourceManager_v1p0_r18_04082019_pub.pdf). IT describes the physical capabilities and defines what kind of work the Tab and RM can do for the upper TSS layers.

2021-09-12 17:58 UTC, klausenbusk commented on trusted_execution/tpm.md
> +The command transmission interface is responsible for creating the transmission context between the higher and lower layers of the stack. Because the context is linking the message receiver and respo
```suggestion
[The command transmission interface](https://trustedcomputinggroup.org/wp-content/uploads/TCG_TSS_TCTI_v1p0_r18_pub.pdf) is responsible for creating the transmission context between the higher and lower layers of the stack. Because the context is linking the message receiver and responder including sending it, this layer resembles the principles of OSIM layer 3, 4 and 5.
```

2021-09-12 17:58 UTC, klausenbusk commented on trusted_execution/tpm.md
> +[SAPI specification pdf](https://trustedcomputinggroup.org/wp-content/uploads/TSS_SAPI_v1p1_r29_pub_20190806.pdf)
```suggestion
On top of that TCG has created the [TSS API (SAPI) specification](https://trustedcomputinggroup.org/wp-content/uploads/TSS_SAPI_v1p1_r29_pub_20190806.pdf) as an abstraction layer so that users docent have to write the raw instructions for the Tab and thereby make it easier for users to control TPM operations. 
```

2021-09-12 17:59 UTC, klausenbusk commented on trusted_execution/tpm.md
> +[FAPI specification pdf](https://trustedcomputinggroup.org/wp-content/uploads/TSS_FAPI_v0p94_r09_pub.pdf)
```suggestion
To increase ease of use the TGC made a specification for a very high level API as an abstraction layer on top of ESAPI that is called the [feature API (FAPI)](https://trustedcomputinggroup.org/wp-content/uploads/TSS_FAPI_v0p94_r09_pub.pdf). This layer does some of the workload for the programmer by making default assumptions about objects and design choices. Which makes it so that 80% of TPM use cases can be programmed by interacting with the FAPI. For the last 20% that has to do custom configurations FAPI would have to be supplied by the other API layers. 
```

2021-09-13 09:40 UTC, klausenbusk commented on trusted_execution/tpm.md
> +It is built as shown in the picture below with a non volatile storage to keep our certificates and encryption keys, a set of secure platform registers for hash values, and a interface enabling us to
```suggestion
It is built as shown in the picture below with a non volatile storage to keep our certificates and encryption keys, a set of secure platform registers for hash values, and a interface enabling us to operate it. ![TPM Architecture](../images/TPM_Architecture.jpg)
```

2021-09-13 09:42 UTC, klausenbusk commented on trusted_execution/tpm.md
> +The result is a hardened chain of trust from secure boot to TPM measurements by utilizing the access to the Intel's chipset. Intel® Trusted Execution Technology  (Intel® TXT) Enabling Guide
Missing link here? (Intel® TXT) Enabling Guide)

2021-09-13 09:45 UTC, klausenbusk commented on trusted_execution/tpm.md
> +A TPM is some kind of tamper-resistant techonology that can perform cryptographic operations (including key generation) and protect small amounts of sensitive information, such aspasswords and crypto
```suggestion
A TPM is some kind of tamper-resistant techonology that can perform cryptographic operations (including key generation) and protect small amounts of sensitive information, such as passwords and cryptographic keys.
```

2021-09-13 11:39 UTC, jacobcrawford requested changes
Add a menupoint in the README.md so that we can locate this piece of documentation.
![image](https://user-images.githubusercontent.com/22328547/133077032-022fd67e-8865-450d-bd2a-5437832d7e2e.png)

2021-09-13 11:41 UTC, jaxels10 requested changes
I have left some suggestions for changes

2021-09-13 11:41 UTC, jaxels10 commented on trusted_execution/tpm.md
> +We have needs for a safe place keep encryption keys, certificates and hash values in the boot process. the tool needs to have some kind of non volatile memmory and it should be able for us to communi
```suggestion
We have needs for a safe place to keep encryption keys, certificates and hash values in the boot process. The tool needs to have some kind of non volatile memory and it should be easy for us to communicate with.
```

2021-09-13 11:41 UTC, jaxels10 commented on trusted_execution/tpm.md
> +TPM follows a ISO standard created by TCG to ensure a standardized way for platform owners to use hardware security to validate software operations.
```suggestion
TPM follows an ISO standard created by TCG to ensure a standardized way for platform owners to use hardware security to validate software operations.
```

2021-09-13 11:41 UTC, jaxels10 commented on trusted_execution/tpm.md
> +To ensure a standardized way of operating a TPM, TCG created following TPM 2.0 ISO standard which describes an operations library TPM creators must implement: Publicly Available Standards
```suggestion
To ensure a standardized way of operating a TPM, TCG created the following TPM 2.0 ISO standard which describes an operations library TPM creators must implement: Publicly Available Standards 
```

2021-09-13 11:41 UTC, jaxels10 commented on trusted_execution/tpm.md
> +The ISO standard is derived out of the specifications that makes up the TCG software stack 2.0
```suggestion
The ISO standard is derived from the specifications that makes up the TCG software stack 2.0
```

2021-09-13 11:41 UTC, jaxels10 commented on trusted_execution/tpm.md
> +First off we have the [Tab (TPM access broker) and resource manager (RM) specification](https://trustedcomputinggroup.org/wp-content/uploads/TSS_2p0_TAB_ResourceManager_v1p0_r18_04082019_pub.pdf). IT
```suggestion
First off, we have the [Tab (TPM access broker) and resource manager (RM) specification](https://trustedcomputinggroup.org/wp-content/uploads/TSS_2p0_TAB_ResourceManager_v1p0_r18_04082019_pub.pdf). It describes the physical capabilities and defines what kind of work the Tab and RM can do for the upper TSS layers.
```

2021-09-13 11:41 UTC, jaxels10 commented on trusted_execution/tpm.md
> +[The command transmission interface (TCTI)](https://trustedcomputinggroup.org/wp-content/uploads/TCG_TSS_TCTI_v1p0_r18_pub.pdf) is responsible for creating the transmission context between the higher
"Because the context is linking the message receiver and responder including sending it"

What is "it" in this context? I have a hard time inferring that

2021-09-13 11:41 UTC, jaxels10 commented on trusted_execution/tpm.md
> +To encrease the ease of use TGC made a very high level API as an abstraction layer on top of ESAPI that is called the [feature API (FAPI)](https://trustedcomputinggroup.org/wp-content/uploads/TSS_FAP
```suggestion
To increase the ease of use, TGC made a high level API as an abstraction layer on top of ESAPI that is called the [feature API (FAPI)](https://trustedcomputinggroup.org/wp-content/uploads/TSS_FAPI_v0p94_r09_pub.pdf). This layer does some of the workload for the programmer by making default assumptions about objects and design choices. This makes it so that 80% of TPM use cases can be programmed by interacting with the FAPI. For the last 20% that has to do custom configurations, FAPI would have to be supplied by the other API layers. 
```

2021-09-13 11:41 UTC, jaxels10 commented on trusted_execution/tpm.md
> +Intel® TXT creates a secured environment for each application to run, which protects an application against software attacks from outside the environment Intel® Trusted Execution Technology (Intel® T
```
Intel® TXT creates a secured environment for each application to run, which protects an application against software attacks from outside the environment Intel® Trusted Execution Technology (Intel® TXT) Overview .
```
What does the last part after the word "environment" mean? It seems like it should have been a headline or a link

2021-09-13 11:41 UTC, jaxels10 commented on trusted_execution/tpm.md
> +That should also make us able to create operation policies based on security clearances. In short we can defines which processor are allowed to perform tasks with higher security clearance.
```suggestion
That should also make us able to create operation policies based on security clearances. In short we can defines which processor is allowed to perform tasks with higher security clearance.
```

2021-09-13 11:41 UTC, jaxels10 commented on trusted_execution/tpm.md
> +Because the stack uses the tool [TrouSerS](https://sourceforge.net/p/trousers/trousers/ci/master/tree/) It is unclear if this stack supports the 64 bit architecture and TPM 2.0.
```suggestion
Because the stack uses the tool [TrouSerS](https://sourceforge.net/p/trousers/trousers/ci/master/tree/) it is unclear if this stack supports the 64 bit architecture and TPM 2.0.
```

2021-09-13 13:08 UTC, SomeFriendlyGhost commented on trusted_execution/tpm.md
> +[The command transmission interface (TCTI)](https://trustedcomputinggroup.org/wp-content/uploads/TCG_TSS_TCTI_v1p0_r18_pub.pdf) is responsible for creating the transmission context between the higher
expanded on the hole subject and the meaning of "it" reffering to the message being sendt between sender and responder

2021-09-13 13:12 UTC, SomeFriendlyGhost commented on trusted_execution/tpm.md
> +Intel® TXT creates a secured environment for each application to run, which protects an application against software attacks from outside the environment Intel® Trusted Execution Technology (Intel® T
it was supposed to be a link

2021-09-14 05:14 UTC, jaxels10 submitted a review, later dismissed
I think this looks good in the current state

2021-09-14 09:39 UTC, jacobcrawford requested changes
Fix path.

2021-09-14 09:39 UTC, jacobcrawford commented on README.md
> +- [Secure Boot](mukube/TrustedExecutionEnvironment/secure-boot.md)
The path is wrong. There is no folder "TrustedExecutionEnvironmen", as it is called "trusted_execution"

2021-09-14 10:05 UTC, jacobcrawford submitted a review, later dismissed
LGTM

2021-09-14 10:07 UTC, jaxels10 approved these changes
LGTM

2021-09-14 10:09 UTC, jacobcrawford approved these changes
LGTM

2021-09-14 10:13 UTC, jacobcrawford approved these changes
LGTM

2021-09-14 10:14 UTC, jaxels10 approved these changes
LGTM

2021-09-14 10:20 UTC, skovbakke approved these changes
LGTM

2021-09-14 10:23 UTC, merged