Release wf v1
distributed-technologies/wiki pull request #3
Opened 2021-03-03 10:04 UTC by jacobcrawford

2021-03-04 09:43 UTC, MartinSchmidt requested changes
Minor fix, missing empty line at end of .yaml file.

2021-03-04 09:43 UTC, MartinSchmidt commented on templates/github-workflows/build_release_helm_chart.yaml
> +          asset_content_type: application/zip
- [ ] Missing empty line at end.

2021-03-04 12:04 UTC, MartinSchmidt requested changes
I left a few comments, on things that should be looked at.

2021-03-04 12:04 UTC, MartinSchmidt commented on templates/github-workflows/build_release_helm_chart.yaml
> +
- [ ] Missing step, move git version tag to new commit.

Maybe update and commit should only run if there were any changes to the file.

2021-03-04 12:04 UTC, MartinSchmidt commented on templates/github-workflows/build_release_helm_chart.yaml
> +          asset_name: ./${{ env.CHART_NAME }}-${{ steps.previoustag.outputs.tag }}.tgz
Question: should the name also have a ./ ? since it is the name of the asset?

2021-03-04 13:53 UTC, jacobcrawford commented on templates/github-workflows/build_release_helm_chart.yaml
> +          asset_name: ./${{ env.CHART_NAME }}-${{ steps.previoustag.outputs.tag }}.tgz
I am not sure what you mean.

2021-03-04 14:13 UTC, MartinSchmidt approved these changes

2021-03-04 14:40 UTC, skovbakke commented on templates/github-workflows/build_release_helm_chart.yaml
> +          asset_content_type: application/zip
- [ ] Still empty line at the end.

2021-03-04 14:40 UTC, skovbakke requested changes
Still no empty line at the end.

2021-03-04 19:26 UTC, skovbakke approved these changes

2021-03-05 06:42 UTC, MartinSchmidt approved these changes

2021-03-05 06:53 UTC, merged