Init helm chartbest practices
distributed-technologies/wiki pull request #9
Opened 2021-03-10 08:43 UTC by jacobcrawford

Here we will discuss the best practices of helm charts. When we decide on a best practice on any subdomain of helm e.g. namespaces, version numbering, usage of quotes, we will merge the pull request into main and keep the branch open for further discussion.

2021-03-10 14:04 UTC, jaxels10 commented on helm/structure.md
> +All our helm charts will always contain 1 folder ´charts´ with the following content:
To elaborate in case it was unclear, "charts" is a reserved folder name in your chart directory: https://helm.sh/docs/topics/charts/. From the example on this webpage, I believe what they call "Wordpress" is what we want to call "chart".

2021-03-10 16:05 UTC, jacobcrawford commented on helm/structure.md
> +All our helm charts will always contain 1 folder ´charts´ with the following content:
I agree. I see that it is also already how the other repos are structured.

2021-03-19 10:34 UTC, MartinSchmidt commented
I have updated the helm documentation, hope you guys agree with the updated version.

2021-03-19 10:58 UTC, skovbakke submitted a review, later dismissed
Very reasonable

2021-03-22 10:30 UTC, jaxels10 requested changes

2021-03-22 10:30 UTC, jaxels10 commented on helm/index.md
> +our clusters will be so through helm.
will be done through helm? Will be through helm?

2021-03-22 10:30 UTC, jaxels10 commented on helm/index.md
> +only require to changes to the values file we will **reference**
delete "to"

2021-03-22 10:30 UTC, jaxels10 commented on helm/index.md
> +In the example with argo-cd everything in the argo-cd: will be forwarded
delete :

2021-03-22 10:30 UTC, jaxels10 commented on helm/index.md
> +and projected on top of the default values file in the subchart.
and will overwrite the values in the values.yaml file in the subchart?

2021-03-22 10:30 UTC, jaxels10 commented on helm/index.md
> +More can be read here: https://helm.sh/docs/chart_template_guide/subcharts_and_globals/
Should this be a link instead of just text?

2021-06-29 08:28 UTC, skovbakke approved these changes
Quite nice now

2021-06-29 08:31 UTC, jaxels10 approved these changes
This looks good.

2021-06-29 08:31 UTC, merged